#!/usr/bin/env sh

set -e
set -x

env="RAILS_ENV=test"

export DISPLAY=:99.0
bundle exec rake db:drop db:create db:migrate $env
bundle exec rake test $env | \
	grep ".* tests, .* assertions, .* failures, .* errors, .* skips" | \
	grep ", [^0]* failures, [^0]* errors" \
	&& exit 1 || exit 0
	# FIXME: the above is a temporary hack to work around Rails bug:
	# https://github.com/rails/rails/issues/4923
